support for user encryption keys

diff --git a/target/bin/addmailuser b/target/bin/addmailuser
--- a/target/bin/addmailuser
+++ b/target/bin/addmailuser
@@ -15,9 +15,12 @@ function __usage
     addmailuser - add an email address (i.e. a user)
 
 \e[38;5;214mSYNOPSIS\e[39m
-    ./setup.sh email add <EMAIL ADDRESS> [<PASSWORD>]
+    ./setup.sh email add [-g] <EMAIL ADDRESS> [<PASSWORD>]
 
 \e[38;5;214mOPTIONS\e[39m
+    -g
+        Also generate user encryption key and password protect it with doveadm mailbox cryptokey generate
+
     \e[94mGeneric Program Information\e[39m
         help       Print the usage information.
 
@@ -35,9 +38,21 @@ function __usage
 
 [[ ${1:-} == 'help' ]] && { __usage ; exit 0 ; }
 
+while getopts "g" OPT
+do
+  case ${OPT} in
+    g ) CRYPTOKEY_GENERATE=true ;;
+    * )
+      echo "Invalid option: -${OPT}" >&2
+      ;;
+  esac
+done
+shift $(( OPTIND - 1 ))
+
 FULL_EMAIL="${1}"
 shift
 PASSWD="${*}"
+CRYPTOKEY_GENERATE="${CRYPTOKEY_GENERATE:-false}"
 
 [[ -z ${FULL_EMAIL} ]] && { __usage ; errex 'No username specified' ; }
 [[ "${FULL_EMAIL}" =~ .*\@.* ]] || { __usage ; errex 'Username must include the domain' ; }
@@ -72,4 +87,10 @@ then
     echo "Waiting for dovecot to create /var/mail/${DOMAIN}/${USER}..."
     sleep 1
   done
+fi
+
+# Only necessary when user encryption keys are enabled
+if "${CRYPTOKEY_GENERATE}"
+then
+  doveadm -o plugin/mail_crypt_private_password="${PASSWD}" mailbox cryptokey generate -u "${FULL_EMAIL}" -U
 fi
diff --git a/target/bin/updatemailuser b/target/bin/updatemailuser
--- a/target/bin/updatemailuser
+++ b/target/bin/updatemailuser
@@ -10,25 +10,57 @@
 
 DATABASE=${DATABASE:-/tmp/docker-mailserver/postfix-accounts.cf}
 
-USER="${1}"
+CRYPTOKEY_UPDATE_PASSWORD=false
+CRYPTOKEY_GENERATE=false
+
+while getopts "cg" OPT
+do
+  case ${OPT} in
+    c ) CRYPTOKEY_UPDATE_PASSWORD="${3}" ;;
+    g ) CRYPTOKEY_GENERATE=true ;;
+    * )
+      echo "Invalid option: -${OPT}" >&2
+      ;;
+  esac
+done
+shift $(( OPTIND - 1 ))
+
+FULL_EMAIL="${1}"
 shift
 PASSWD="${*}"
 
-function usage  {	echo "Usage: updatemailuser <user@domain.tld> [password]" ; }
+function usage  {	echo "Usage: updatemailuser [-g] [-c] <EMAIL ADDRESS> [<PASSWORD>] [<OLD CRYPTOKEY PASSWORD>]" ; }
 
-[[ -z ${USER} ]] && { usage ; errex "no username specified" ; }
+[[ -z ${FULL_EMAIL} ]] && { usage ; errex "no username specified" ; }
 
 if [[ -z ${PASSWD} ]]
 then
   read -r -s -p "Enter Password: " PASSWD
   echo
-  [[ -z ${PASSWD} ]] && errex "Password must not be empty"
+  [[ -z ${PASSWD} ]] && errex "password must not be empty"
 fi
 
-HASH="$(doveadm pw -s SHA512-CRYPT -u "${USER}" -p "${PASSWD}")"
+HASH="$(doveadm pw -s SHA512-CRYPT -u "${FULL_EMAIL}" -p "${PASSWD}")"
 
 # Protect config file with lock to avoid race conditions
 touch "${DATABASE}"
 create_lock "$(basename "$0")"
-grep -qi "^$(escape "${USER}")|" "${DATABASE}" 2>/dev/null || errex "User \"${USER}\" does not exist"
-sed -i "s ^""${USER}""|.* ""${USER}""|""${HASH}"" " "${DATABASE}"
+grep -qi "^$(escape "${FULL_EMAIL}")|" "${DATABASE}" 2>/dev/null || errex "user \"${FULL_EMAIL}\" does not exist"
+sed -i "s ^""${FULL_EMAIL}""|.* ""${FULL_EMAIL}""|""${HASH}"" " "${DATABASE}"
+
+# Only necessary when FULL_EMAIL encryption keys are enabled
+if [[ "${CRYPTOKEY_UPDATE_PASSWORD}" != false ]]
+then
+    if [[ -z ${CRYPTOKEY_UPDATE_PASSWORD} ]]
+    then
+      read -r -s -p "Enter Old CryptoKey Password: " CRYPTOKEY_UPDATE_PASSWORD
+      echo
+      [[ -z ${CRYPTOKEY_UPDATE_PASSWORD} ]] && errex "password must not be empty"
+    fi
+    doveadm mailbox cryptokey password -u "${FULL_EMAIL}" -n "${PASSWD}" -o "${CRYPTOKEY_UPDATE_PASSWORD}"
+fi
+
+if "${CRYPTOKEY_GENERATE}"
+then
+  doveadm -o plugin/mail_crypt_private_password="${PASSWD}" mailbox cryptokey generate -u "${FULL_EMAIL}" -U
+fi
